### ISSUE TITLE
給与の公開

### ISSUE THREAD

**Issue by YutaGoto** [pocke/salary#1]
すごいリポジトリだと思いました。

個人の給与は個人情報のひとつなので、自分の給与を公開しても問題ないものかちょっときになりました。。

**Comment by pocke** [comment]
ありがとうございます🙏

> 個人の給与は個人情報のひとつなので、自分の給与を公開しても問題ないものかちょっときになりました。。

他にも同様のことをやっている人は結構いる(具体例は出しませんが)のと、私のスタンスとしては公開されていても問題ないと思っているので、とくに問題はないかなと思っています。
どこかから怒られが発生したら公開を取りやめる可能性もありますが、今の所そういうこともないので。。

一応、給与以外の所得を公開する予定は今の所ありません(算出がめんどいというのもある)

**Comment by YutaGoto** [comment]
なるほど。。。
所属していた企業から注意がなくて本人がOKであれば、そこまで問題ないんですね。

給与以外の収入の計算はたしかにめんどいですね。。わかります。

/issue close
